# -*- coding: utf-8 -*-
"""Untitled8.project1-first pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZXHDrDNIJb6SqI0X57yZHMRhpNFjTyxI

First Mini Project

⁠Project Option 1: Console-Based Smart Calculator
"""

import numpy as np

print(" Smart Calculator ")
print("1. Addition")
print("2. Subtraction")
print("3. Multiplication")
print("4. Division")
print("5. Power Calculation")
print("6. Modulus Operation")

choice = int(input("Enter your choice (1-6): "))

n = int(input("How many numbers do you want to enter? "))

nums = []
for i in range(n):
    nums.append(float(input(f"Enter number {i+1}: ")))

# storing in NumPy array
arr = np.array(nums)

# Operations using looping method
if choice == 1:  # Addition
    result = 0
    for num in arr:
        result += num
    print("Result:", result)

elif choice == 2:  # Subtraction
    result = arr[0]
    for i in range(1, len(arr)):
        result -= arr[i]
    print("Result:", result)

elif choice == 3:  # Multiplication
    result = 1
    for num in arr:
        result *= num
    print("Result:", result)

elif choice == 4:  # Division
    result = arr[0]
    for i in range(1, len(arr)):
        if arr[i] == 0:
            print("Cannot divide by zero!")
            break
        result /= arr[i]
    else:
        print("Result:", result)

elif choice == 5:  # Power
    result = arr[0]
    for i in range(1, len(arr)):
        result = result ** arr[i]
    print("Result:", result)

elif choice == 6:  # Modulus
    result = arr[0]
    for i in range(1, len(arr)):
        if arr[i] == 0:
            print("Cannot do modulus by zero!")
            break
        result %= arr[i]
    else:
        print("Result:", result)

else:
    print("Invalid choice! Please choose between 1 to 6.")

"""Project Option 2: Student marks analyzer"""

#Student Marks Analyzer
import numpy as np

n = int(input("Enter the number of students: "))

marks_list = []  # empty list to store the marks
grades = [] # empty list to store the grades

for i in range(n):
    marks = int(input(f"Enter marks of student {i+1}: "))
    marks_list.append(marks)

    while marks < 0 or marks > 100:
        print("Invalid marks! Enter between 0 and 100.")
        marks = int(input(f"Enter marks of student {i+1}: "))


    # Calculating grades and adding them to the list for the current student
    if marks >= 90:
        grades.append("A")
    elif marks >= 75:
        grades.append("B")
    elif marks >= 50:
        grades.append("C")
    else:
        grades.append("Fail")

print()   # To give a line space in the output
for i in range(n):    # Printing the grades along with the marks
 print(f"Student {i+1} - Marks: {marks_list[i]}, Grade: {grades[i]}")
arr = np.array(marks_list)   # Array of marks - Use marks_list


print()
print(f"Total Marks   : {np.sum(arr)}")
print(f"Average Marks : {np.mean(arr)}")
print(f"Highest Marks : {np.max(arr)}")
print(f"Lowest Marks  : {np.min(arr)}")
print(f"Median Marks  : {np.median(arr)}")